def get_forecast(latitude: float, longitude: float):
  return {
    "location": {
      "latitude": latitude,
      "longitude": longitude,
    },
    "daily": [
      {
        "id": 1,
        "day": "Mon",
        "date": "May 27",
        "weather": "Sunny",
        "score": 82,
        "label": "Excellent",
        "temperature": "12°C",
        "reasons": ["Low rain chance", "Mild temperature", "Light wind"],
      },
      {
        "id": 2,
        "day": "Tue",
        "date": "May 28",
        "weather": "Partly cloudy",
        "score": 74,
        "label": "Good",
        "temperature": "14°C",
        "reasons": ["Low rain chance", "Comfortable temp", "Light wind"],
      },
      {
        "id": 3,
        "day": "Wed",
        "date": "May 29",
        "weather": "Cloudy",
        "score": 61,
        "label": "Fair",
        "temperature": "10°C",
        "reasons": ["Some cloud cover", "Slight chance rain", "Moderate wind"],
      },
      {
        "id": 4,
        "day": "Thu",
        "date": "May 30",
        "weather": "Rainy",
        "score": 45,
        "label": "Poor",
        "temperature": "8°C",
        "reasons": ["High rain chance", "Cool temp", "Strong wind"],
      },
      {
        "id": 5,
        "day": "Fri",
        "date": "May 31",
        "weather": "Stormy",
        "score": 30,
        "label": "Very Poor",
        "temperature": "6°C",
        "reasons": ["High rain chance", "Cold temp", "Strong wind"],
      },
      {
        "id": 6,
        "day": "Sat",
        "date": "Jun 1",
        "weather": "Sunny",
        "score": 85,
        "label": "Excellent",
        "temperature": "15°C",
        "reasons": ["Low rain chance", "Mild temperature", "Light wind"],
      },
      {
        "id": 7,
        "day": "Sun",
        "date": "Jun 2",
        "weather": "Partly cloudy",
        "score": 78,
        "label": "Good",
        "temperature": "13°C",
        "reasons": ["Low rain chance", "Comfortable temp", "Light wind"],
      }
    ],
  }